Repository kkn1125/narang, pull requests merged in 2022-07, with the labels that each got.

#7 Kkn1125/add
  src/main/frontend/package.json
  src/main/frontend/src/App.tsx
  src/main/frontend/src/components/atoms/Image.tsx
  src/main/frontend/src/components/organisms/Header.tsx
  src/main/frontend/src/components/templates/Layout.tsx
  src/main/frontend/src/index.tsx
  src/main/frontend/src/pages/About.tsx
  src/main/frontend/src/pages/Home.tsx
  src/main/frontend/yarn.lock
Labels: :wrench: FIX, ✖️ ADD, ✨ FE

#8 Develop
  src/main/frontend/package.json
  src/main/frontend/src/App.tsx
  src/main/frontend/src/components/atoms/Image.tsx
  src/main/frontend/src/components/organisms/Header.tsx
  src/main/frontend/src/components/templates/Layout.tsx
  src/main/frontend/src/index.tsx
  src/main/frontend/src/pages/About.tsx
  src/main/frontend/src/pages/Home.tsx
  src/main/frontend/yarn.lock
Labels: 🔮 SYNC

#12 Kkn1125/add
  src/main/frontend/package.json
  src/main/frontend/src/App.tsx
  src/main/frontend/src/components/atoms/Image.tsx
  src/main/frontend/src/components/molecules/AvatarBox.tsx
  src/main/frontend/src/components/molecules/MessageBox.tsx
  src/main/frontend/src/components/molecules/SearchBar.tsx
  src/main/frontend/src/components/organisms/DrawerBlock.tsx
  src/main/frontend/src/components/templates/DiaryLayout.tsx
  src/main/frontend/src/index.tsx
  src/main/frontend/src/pages/Diary/Graph.tsx
  src/main/frontend/src/pages/Diary/Recommend.tsx
  src/main/frontend/src/pages/Diary/Share.tsx
  src/main/frontend/src/pages/Diary/Usage.tsx
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/frontend/src/pages/Home.tsx
  src/main/frontend/src/pages/NotFound.tsx
  src/main/frontend/src/svg/NotFound.svg
  src/main/frontend/src/tools/models.ts
  src/main/frontend/yarn.lock
Labels: ✖️ ADD, ✨ FE

#13 Develop
  src/main/frontend/package.json
  src/main/frontend/src/App.tsx
  src/main/frontend/src/components/atoms/Image.tsx
  src/main/frontend/src/components/molecules/AvatarBox.tsx
  src/main/frontend/src/components/molecules/MessageBox.tsx
  src/main/frontend/src/components/molecules/SearchBar.tsx
  src/main/frontend/src/components/organisms/DrawerBlock.tsx
  src/main/frontend/src/components/templates/DiaryLayout.tsx
  src/main/frontend/src/index.tsx
  src/main/frontend/src/pages/Diary/Graph.tsx
  src/main/frontend/src/pages/Diary/Recommend.tsx
  src/main/frontend/src/pages/Diary/Share.tsx
  src/main/frontend/src/pages/Diary/Usage.tsx
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/frontend/src/pages/Home.tsx
  src/main/frontend/src/pages/NotFound.tsx
  src/main/frontend/src/svg/NotFound.svg
  src/main/frontend/src/tools/models.ts
  src/main/frontend/yarn.lock
Labels: 🔮 SYNC

#14 Ohoraming/add2
  src/main/frontend/package-lock.json
  src/main/frontend/src/components/atoms/Image.tsx
  src/main/frontend/src/components/atoms/Title.tsx
  src/main/frontend/src/components/molecules/IconSet.tsx
  src/main/frontend/src/components/organisms/Header.tsx
  src/main/frontend/src/components/templates/Layout.tsx
  src/main/frontend/src/pages/Home.tsx
  src/main/frontend/yarn.lock
Labels: ✖️ ADD, ✨ FE, :white_check_mark: CHECK

#15 Kkn1125/add
  src/main/frontend/src/App.tsx
  src/main/frontend/src/components/molecules/AuthTitle.tsx
  src/main/frontend/src/components/molecules/SocialSignIn.tsx
  src/main/frontend/src/components/molecules/TermsConditions.tsx
  src/main/frontend/src/components/molecules/TextFieldSet.tsx
  src/main/frontend/src/components/templates/AuthLayout.tsx
  src/main/frontend/src/index.tsx
  src/main/frontend/src/pages/Auth/SignIn.tsx
  src/main/frontend/src/pages/Auth/SignUp.tsx
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/src/tools/utils.ts
Labels: :wrench: FIX, ✖️ ADD, ✨ FE

#16 Develop
  src/main/frontend/package-lock.json
  src/main/frontend/src/App.tsx
  src/main/frontend/src/components/atoms/Image.tsx
  src/main/frontend/src/components/atoms/Title.tsx
  src/main/frontend/src/components/molecules/AuthTitle.tsx
  src/main/frontend/src/components/molecules/IconSet.tsx
  src/main/frontend/src/components/molecules/SocialSignIn.tsx
  src/main/frontend/src/components/molecules/TermsConditions.tsx
  src/main/frontend/src/components/molecules/TextFieldSet.tsx
  src/main/frontend/src/components/organisms/Header.tsx
  src/main/frontend/src/components/templates/AuthLayout.tsx
  src/main/frontend/src/components/templates/Layout.tsx
  src/main/frontend/src/index.tsx
  src/main/frontend/src/pages/Auth/SignIn.tsx
  src/main/frontend/src/pages/Auth/SignUp.tsx
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/src/pages/Home.tsx
  src/main/frontend/src/tools/utils.ts
  src/main/frontend/yarn.lock
Labels: 🔮 SYNC

#17 Kkn1125/add
  src/main/frontend/package.json
  src/main/frontend/src/pages/Auth/SignIn.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/frontend/yarn.lock
Labels: :wrench: FIX, ✖️ ADD, ❌ DELETE, ✨ FE

#18 Develop
  src/main/frontend/package.json
  src/main/frontend/src/pages/Auth/SignIn.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/frontend/yarn.lock
Labels: 🔮 SYNC

#23 Ohoraming/add
  src/main/frontend/src/pages/Diary/WriteForm.tsx
Labels: ✖️ ADD, :white_check_mark: CHECK

#28 Ohoraming/add
  src/main/frontend/package.json
  src/main/frontend/src/pages/Diary/Graph.tsx
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/yarn.lock
Labels: ✖️ ADD, ✨ FE, :white_check_mark: CHECK, :exclamation: PROBLEM

#29 Kkn1125/fix
  src/main/frontend/package.json
  src/main/frontend/src/pages/Diary/Graph.tsx
Labels: :wrench: FIX, ✖️ ADD, ✨ FE, :white_check_mark: CHECK

#34 Kkn1125/main/fix
  src/main/frontend/src/components/atoms/Image.tsx
  src/main/frontend/src/components/atoms/Title.tsx
  src/main/frontend/src/components/molecules/FooterMenuList.tsx
  src/main/frontend/src/components/molecules/IconSet.tsx
  src/main/frontend/src/components/organisms/DynamicSection.tsx
  src/main/frontend/src/components/organisms/Footer.tsx
  src/main/frontend/src/components/organisms/Header.tsx
  src/main/frontend/src/components/templates/Layout.tsx
  src/main/frontend/src/pages/Home.tsx
Labels: :wrench: FIX, ✖️ ADD, :hammer_and_wrench: UPDATE, ❌ DELETE, ✨ FE

#33 Kkn1125/fix
  src/main/frontend/package-lock.json
  src/main/frontend/package.json
  src/main/frontend/src/components/molecules/TextFieldSet.tsx
  src/main/frontend/src/components/organisms/SignControl.tsx
  src/main/frontend/src/pages/Auth/SignIn.tsx
  src/main/frontend/src/pages/Auth/SignUp.tsx
  src/main/frontend/src/pages/Diary/Usage.tsx
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/src/setupProxy.js
  src/main/frontend/src/setupProxy.ts
  src/main/frontend/src/tools/analyzer.ts
  src/main/frontend/tsconfig.json
  src/main/frontend/yarn.lock
Labels: :lady_beetle: BUGFIX, :wrench: FIX, ✖️ ADD, :hammer_and_wrench: UPDATE, ✨ FE

#35 Develop
  src/main/frontend/package-lock.json
  src/main/frontend/package.json
  src/main/frontend/src/components/atoms/Image.tsx
  src/main/frontend/src/components/atoms/Title.tsx
  src/main/frontend/src/components/molecules/FooterMenuList.tsx
  src/main/frontend/src/components/molecules/IconSet.tsx
  src/main/frontend/src/components/molecules/TextFieldSet.tsx
  src/main/frontend/src/components/organisms/DynamicSection.tsx
  src/main/frontend/src/components/organisms/Footer.tsx
  src/main/frontend/src/components/organisms/Header.tsx
  src/main/frontend/src/components/organisms/SignControl.tsx
  src/main/frontend/src/components/templates/Layout.tsx
  src/main/frontend/src/pages/Auth/SignIn.tsx
  src/main/frontend/src/pages/Auth/SignUp.tsx
  src/main/frontend/src/pages/Diary/Usage.tsx
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/src/pages/Home.tsx
  src/main/frontend/src/setupProxy.js
  src/main/frontend/src/setupProxy.ts
  src/main/frontend/src/tools/analyzer.ts
  src/main/frontend/tsconfig.json
  src/main/frontend/yarn.lock
Labels: 🔮 SYNC

#38 Ohoraming/add2
  src/main/frontend/src/pages/Diary/Recommend.tsx
Labels: ✖️ ADD, ✨ FE, :white_check_mark: CHECK

#39 Develop
  src/main/frontend/src/pages/Diary/Recommend.tsx
Labels: 🔮 SYNC

#40 Develop
  src/main/frontend/src/components/common/WavesBG.tsx
  src/main/frontend/src/pages/About.tsx
  src/main/frontend/src/theme.ts
Labels: 🔮 SYNC

#43 Kkn1125/be/feat
  build.gradle
  src/main/java/com/narang/web/entity/User.java
  src/main/java/com/narang/web/mongoTemplate/UserTemplate.java
  src/main/java/com/narang/web/restController/UserRestController.java
Labels: :wrench: FIX, ✖️ ADD, ⚙️ BE

#44 Develop
  build.gradle
  src/main/java/com/narang/web/entity/User.java
  src/main/java/com/narang/web/mongoTemplate/UserTemplate.java
  src/main/java/com/narang/web/restController/UserRestController.java
Labels: 🔮 SYNC

#46 Ohoraming/add
  src/main/frontend/src/App.tsx
  src/main/frontend/src/components/molecules/AvatarBox.tsx
  src/main/frontend/src/pages/Auth/Profile.tsx
Labels: ✖️ ADD, ✨ FE, :white_check_mark: CHECK

#48 Kkn1125/be/add
  build.gradle
  src/main/frontend/.env
  src/main/frontend/src/apis/auth.ts
  src/main/frontend/src/components/molecules/FooterMenuList.tsx
  src/main/frontend/src/components/molecules/TermsConditions.tsx
  src/main/frontend/src/components/molecules/TextFieldSet.tsx
  src/main/frontend/src/components/organisms/DrawerBlock.tsx
  src/main/frontend/src/components/organisms/Footer.tsx
  src/main/frontend/src/components/organisms/Header.tsx
  src/main/frontend/src/envPath.ts
  src/main/frontend/src/models/IModel.ts
  src/main/frontend/src/models/MenuItem.ts
  src/main/frontend/src/models/User.ts
  src/main/frontend/src/pages/Auth/SignUp.tsx
  src/main/frontend/src/setupProxy.js
  src/main/java/com/narang/web/entity/User.java
  src/main/java/com/narang/web/mongoTemplate/CrudTemplate.java
  src/main/java/com/narang/web/mongoTemplate/UserTemplate.java
  src/main/java/com/narang/web/restController/UserRestController.java
  src/test/java/com/narang/web/restController/UserRestControllerTest.java
Labels: :wrench: FIX, ✖️ ADD, :hammer_and_wrench: UPDATE, ❌ DELETE, ✨ FE, ⚙️ BE, :exclamation: PROBLEM

#49 Develop
  build.gradle
  src/main/frontend/.env
  src/main/frontend/src/App.tsx
  src/main/frontend/src/apis/auth.ts
  src/main/frontend/src/components/molecules/AvatarBox.tsx
  src/main/frontend/src/components/molecules/FooterMenuList.tsx
  src/main/frontend/src/components/molecules/TermsConditions.tsx
  src/main/frontend/src/components/molecules/TextFieldSet.tsx
  src/main/frontend/src/components/organisms/DrawerBlock.tsx
  src/main/frontend/src/components/organisms/Footer.tsx
  src/main/frontend/src/components/organisms/Header.tsx
  src/main/frontend/src/envPath.ts
  src/main/frontend/src/models/IModel.ts
  src/main/frontend/src/models/MenuItem.ts
  src/main/frontend/src/models/User.ts
  src/main/frontend/src/pages/Auth/Profile.tsx
  src/main/frontend/src/pages/Auth/SignUp.tsx
  src/main/frontend/src/setupProxy.js
  src/main/java/com/narang/web/entity/User.java
  src/main/java/com/narang/web/mongoTemplate/CrudTemplate.java
  src/main/java/com/narang/web/mongoTemplate/UserTemplate.java
  src/main/java/com/narang/web/restController/UserRestController.java
  src/test/java/com/narang/web/restController/UserRestControllerTest.java
Labels: 🔮 SYNC

#50 Kkn1125/hotfix
  src/main/frontend/src/components/molecules/AvatarBox.tsx
  src/main/frontend/src/components/organisms/Header.tsx
  src/main/frontend/src/pages/About.tsx
Labels: :lady_beetle: BUGFIX, :hammer_and_wrench: UPDATE, ✨ FE

#51 Develop
  src/main/frontend/src/components/molecules/AvatarBox.tsx
  src/main/frontend/src/components/organisms/Header.tsx
  src/main/frontend/src/pages/About.tsx
Labels: 🔮 SYNC

#56 Kkn1125/be/feat
  src/main/frontend/package.json
  src/main/frontend/src/App.tsx
  src/main/frontend/src/apis/auth.ts
  src/main/frontend/src/apis/auth/index.ts
  src/main/frontend/src/apis/auth/types.ts
  src/main/frontend/src/apis/commonTypes.ts
  src/main/frontend/src/apis/test/auth.test.tsx
  src/main/frontend/src/apis/user/index.ts
  src/main/frontend/src/apis/user/types.ts
  src/main/frontend/src/models/FaceImage.ts
  src/main/frontend/src/models/IModel.ts
  src/main/frontend/src/models/PModel.ts
  src/main/frontend/src/models/User.ts
  src/main/frontend/src/pages/Auth/SignUp.tsx
  src/main/frontend/src/setupTests.js
  src/main/frontend/src/tools/utils.ts
  src/main/frontend/yarn.lock
  src/main/java/com/narang/web/config/MongoAuditConfig.java
  src/main/java/com/narang/web/config/UserAuditor.java
  src/main/java/com/narang/web/entity/FaceImage.java
  src/main/java/com/narang/web/entity/User.java
  src/main/java/com/narang/web/restController/UserRestController.java
Labels: :lady_beetle: BUGFIX, :wrench: FIX, ✖️ ADD, :hammer_and_wrench: UPDATE, ❌ DELETE, 🗂️ REF, ✨ FE, ⚙️ BE, :exclamation: PROBLEM

#57 Develop
  src/main/frontend/package.json
  src/main/frontend/src/App.tsx
  src/main/frontend/src/apis/auth.ts
  src/main/frontend/src/apis/auth/index.ts
  src/main/frontend/src/apis/auth/types.ts
  src/main/frontend/src/apis/commonTypes.ts
  src/main/frontend/src/apis/test/auth.test.tsx
  src/main/frontend/src/apis/user/index.ts
  src/main/frontend/src/apis/user/types.ts
  src/main/frontend/src/models/FaceImage.ts
  src/main/frontend/src/models/IModel.ts
  src/main/frontend/src/models/PModel.ts
  src/main/frontend/src/models/User.ts
  src/main/frontend/src/pages/Auth/SignUp.tsx
  src/main/frontend/src/setupTests.js
  src/main/frontend/src/tools/utils.ts
  src/main/frontend/yarn.lock
  src/main/java/com/narang/web/config/MongoAuditConfig.java
  src/main/java/com/narang/web/config/UserAuditor.java
  src/main/java/com/narang/web/entity/FaceImage.java
  src/main/java/com/narang/web/entity/User.java
  src/main/java/com/narang/web/restController/UserRestController.java
Labels: 🔮 SYNC, :white_check_mark: CHECK
