Repository kkn1125/narang, pull requests merged in 2022-08, with the labels that each got.

#66 Develop
  src/main/frontend/src/apis/auth/index.ts
  src/main/frontend/src/models/FaceImage.ts
  src/main/frontend/src/models/User.ts
  src/main/frontend/src/pages/Auth/SignUp.tsx
  src/main/java/com/narang/web/WebApplication.java
  src/main/java/com/narang/web/config/MongoAuditConfig.java
  src/main/java/com/narang/web/entity/Comment.java
  src/main/java/com/narang/web/filter/EncodingFilter.java
  src/main/java/com/narang/web/repository/CommentRepository.java
  src/main/java/com/narang/web/repository/UserRepository.java
  src/main/java/com/narang/web/repository/UserRepositoryCustom.java
  src/main/java/com/narang/web/repository/UserRepositoryCustomImpl.java
  src/main/java/com/narang/web/restController/CommentRestController.java
  src/main/java/com/narang/web/restController/TestRestController.java
  src/main/java/com/narang/web/restController/UserRestController.java
Labels: 🔮 SYNC

#70 Kkn1125/fe/feat
  src/main/frontend/package.json
  src/main/frontend/src/App.tsx
  src/main/frontend/src/apis/auth/index.ts
  src/main/frontend/src/apis/comment/index.ts
  src/main/frontend/src/apis/commonTypes.ts
  src/main/frontend/src/apis/diary/index.ts
  src/main/frontend/src/apis/diary/types.ts
  src/main/frontend/src/apis/emotions/index.ts
  src/main/frontend/src/apis/emotions/types.ts
  src/main/frontend/src/components/atoms/OverflowContent.tsx
  src/main/frontend/src/components/molecules/CommentItem.tsx
  src/main/frontend/src/components/molecules/SwitchLabels.tsx
  src/main/frontend/src/components/organisms/CommentInsert.tsx
  src/main/frontend/src/components/organisms/CommentList.tsx
  src/main/frontend/src/components/organisms/UserInfo.tsx
  src/main/frontend/src/components/templates/DetailLayout.tsx
  src/main/frontend/src/models/Comment.ts
  src/main/frontend/src/models/Diary.ts
  src/main/frontend/src/models/Emotions.ts
  src/main/frontend/src/models/FaceImage.ts
  src/main/frontend/src/models/IModel.ts
  src/main/frontend/src/models/Like.ts
  src/main/frontend/src/models/PModel.ts
  src/main/frontend/src/models/User.ts
  src/main/frontend/src/pages/Diary/Detail.tsx
  src/main/frontend/src/pages/Diary/Graph.tsx
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/frontend/src/tools/utils.ts
  src/main/frontend/tsconfig.json
  src/main/frontend/yarn.lock
  src/main/java/com/narang/web/entity/Comment.java
  src/main/java/com/narang/web/mongoTemplate/CrudTemplate.java
  src/main/java/com/narang/web/mongoTemplate/DiaryTemplate.java
  src/main/java/com/narang/web/mongoTemplate/EmotionTemplate.java
  src/main/java/com/narang/web/mongoTemplate/FaceImageTemplate.java
  src/main/java/com/narang/web/mongoTemplate/UserTemplate.java
  src/main/java/com/narang/web/repository/CommentRepository.java
  src/main/java/com/narang/web/repository/CommentRepositoryCustom.java
  src/main/java/com/narang/web/repository/CommentRepositoryCustomImpl.java
  src/main/java/com/narang/web/restController/CommentRestController.java
  src/main/java/com/narang/web/restController/DiaryRestController.java
  src/main/java/com/narang/web/restController/EmotionRestController.java
Labels: :lady_beetle: BUGFIX, ✖️ ADD, :hammer_and_wrench: UPDATE, 📄 TODO, ✨ FE, ⚙️ BE, :white_check_mark: CHECK, :exclamation: PROBLEM

#71 Develop
  src/main/frontend/package.json
  src/main/frontend/src/App.tsx
  src/main/frontend/src/apis/auth/index.ts
  src/main/frontend/src/apis/comment/index.ts
  src/main/frontend/src/apis/commonTypes.ts
  src/main/frontend/src/apis/diary/index.ts
  src/main/frontend/src/apis/diary/types.ts
  src/main/frontend/src/apis/emotions/index.ts
  src/main/frontend/src/apis/emotions/types.ts
  src/main/frontend/src/components/atoms/OverflowContent.tsx
  src/main/frontend/src/components/molecules/CommentItem.tsx
  src/main/frontend/src/components/molecules/SwitchLabels.tsx
  src/main/frontend/src/components/organisms/CommentInsert.tsx
  src/main/frontend/src/components/organisms/CommentList.tsx
  src/main/frontend/src/components/organisms/UserInfo.tsx
  src/main/frontend/src/components/templates/DetailLayout.tsx
  src/main/frontend/src/models/Comment.ts
  src/main/frontend/src/models/Diary.ts
  src/main/frontend/src/models/Emotions.ts
  src/main/frontend/src/models/FaceImage.ts
  src/main/frontend/src/models/IModel.ts
  src/main/frontend/src/models/Like.ts
  src/main/frontend/src/models/PModel.ts
  src/main/frontend/src/models/User.ts
  src/main/frontend/src/pages/Diary/Detail.tsx
  src/main/frontend/src/pages/Diary/Graph.tsx
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/frontend/src/tools/utils.ts
  src/main/frontend/tsconfig.json
  src/main/frontend/yarn.lock
  src/main/java/com/narang/web/entity/Comment.java
  src/main/java/com/narang/web/mongoTemplate/CrudTemplate.java
  src/main/java/com/narang/web/mongoTemplate/DiaryTemplate.java
  src/main/java/com/narang/web/mongoTemplate/EmotionTemplate.java
  src/main/java/com/narang/web/mongoTemplate/FaceImageTemplate.java
  src/main/java/com/narang/web/mongoTemplate/UserTemplate.java
  src/main/java/com/narang/web/repository/CommentRepository.java
  src/main/java/com/narang/web/repository/CommentRepositoryCustom.java
  src/main/java/com/narang/web/repository/CommentRepositoryCustomImpl.java
  src/main/java/com/narang/web/restController/CommentRestController.java
  src/main/java/com/narang/web/restController/DiaryRestController.java
  src/main/java/com/narang/web/restController/EmotionRestController.java
Labels: 🔮 SYNC

#72 Ohoraming/add2
  src/main/java/com/narang/web/entity/Product.java
  src/main/java/com/narang/web/repository/ProductRepository.java
  src/main/java/com/narang/web/restController/ProductRestController.java
Labels: ✖️ ADD, ⚙️ BE

#73 [FE][:wrench: FIX]: 각 모델 get 함수 제거 + PModel에 get 함수 통합
  src/main/frontend/src/models/Comment.ts
  src/main/frontend/src/models/Diary.ts
  src/main/frontend/src/models/Emotions.ts
  src/main/frontend/src/models/FaceImage.ts
  src/main/frontend/src/models/Like.ts
  src/main/frontend/src/models/PModel.ts
  src/main/frontend/src/models/User.ts
Labels: :wrench: FIX, ✨ FE

#74 Develop
  src/main/frontend/src/models/Comment.ts
  src/main/frontend/src/models/Diary.ts
  src/main/frontend/src/models/Emotions.ts
  src/main/frontend/src/models/FaceImage.ts
  src/main/frontend/src/models/Like.ts
  src/main/frontend/src/models/PModel.ts
  src/main/frontend/src/models/User.ts
  src/main/java/com/narang/web/entity/Product.java
  src/main/java/com/narang/web/repository/ProductRepository.java
  src/main/java/com/narang/web/restController/ProductRestController.java
Labels: 🔮 SYNC

#80 Kkn1125/all/feat
  build.gradle
  src/main/frontend/.env
  src/main/frontend/package.json
  src/main/frontend/src/App.tsx
  src/main/frontend/src/apis/auth/index.ts
  src/main/frontend/src/apis/diary/index.ts
  src/main/frontend/src/apis/emotions/index.ts
  src/main/frontend/src/apis/like/index.ts
  src/main/frontend/src/apis/user/types.ts
  src/main/frontend/src/components/atoms/FavoritButton.tsx
  src/main/frontend/src/components/atoms/OverflowContent.tsx
  src/main/frontend/src/components/molecules/AvatarBox.tsx
  src/main/frontend/src/components/organisms/DrawerBlock.tsx
  src/main/frontend/src/components/organisms/SignControl.tsx
  src/main/frontend/src/components/templates/DetailLayout.tsx
  src/main/frontend/src/index.tsx
  src/main/frontend/src/models/MenuItem.ts
  src/main/frontend/src/models/PModel.ts
  src/main/frontend/src/pages/Auth/SignIn.tsx
  src/main/frontend/src/pages/Auth/SignUp.tsx
  src/main/frontend/src/pages/Diary/Cart.tsx
  src/main/frontend/src/pages/Diary/Detail.tsx
  src/main/frontend/src/pages/Diary/Share.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/frontend/yarn.lock
  src/main/java/com/narang/web/WebApplication.java
  src/main/java/com/narang/web/config/MongoAuditConfig.java
  src/main/java/com/narang/web/config/SecurityConfiguration.java
  src/main/java/com/narang/web/entity/Like.java
  src/main/java/com/narang/web/entity/User.java
  src/main/java/com/narang/web/mongoTemplate/EmotionTemplate.java
  src/main/java/com/narang/web/mongoTemplate/LikeTemplate.java
  src/main/java/com/narang/web/mongoTemplate/UserTemplate.java
  src/main/java/com/narang/web/repository/UserRepositoryCustom.java
  src/main/java/com/narang/web/repository/UserRepositoryCustomImpl.java
  src/main/java/com/narang/web/restController/EmotionRestController.java
  src/main/java/com/narang/web/restController/LikeRestController.java
  src/main/java/com/narang/web/restController/UserRestController.java
  src/main/resources/application.properties
Labels: :lady_beetle: BUGFIX, :wrench: FIX, ✖️ ADD, :hammer_and_wrench: UPDATE, 📄 TODO, ✨ FE, ⚙️ BE

#82 Kkn1125/fe/hotfix
  src/main/frontend/.env
  src/main/frontend/.eslintignore
  src/main/frontend/src/App.tsx
  src/main/frontend/src/components/organisms/FaceSign.tsx
  src/main/frontend/src/components/organisms/SignControl.tsx
  src/main/frontend/src/components/templates/AuthLayout.tsx
  src/main/frontend/src/pages/About.tsx
  src/main/frontend/src/pages/Auth/FaceLogin.tsx
  src/main/frontend/src/pages/Auth/SignIn.tsx
  src/main/frontend/tsconfig.json
  yarn.lock
Labels: :lady_beetle: BUGFIX, ✖️ ADD, :hammer_and_wrench: UPDATE, ✨ FE, :white_check_mark: CHECK

#84 Develop
  src/main/frontend/.env
  src/main/frontend/.eslintignore
  src/main/frontend/src/App.tsx
  src/main/frontend/src/components/organisms/FaceSign.tsx
  src/main/frontend/src/components/organisms/SignControl.tsx
  src/main/frontend/src/components/templates/AuthLayout.tsx
  src/main/frontend/src/pages/About.tsx
  src/main/frontend/src/pages/Auth/FaceLogin.tsx
  src/main/frontend/src/pages/Auth/SignIn.tsx
  src/main/frontend/tsconfig.json
  yarn.lock
Labels: 🔮 SYNC

#86 Kkn1125/all/hotfix
  src/main/frontend/src/apis/test/auth.test.tsx
  src/main/frontend/src/apis/user/index.ts
  src/main/frontend/src/components/organisms/SignControl.tsx
  src/main/frontend/src/pages/Diary/Recommend.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/frontend/src/tools/devConsole.ts
  src/main/resources/application.properties
Labels: :lady_beetle: BUGFIX, ✖️ ADD, :hammer_and_wrench: UPDATE, ❌ DELETE, ✨ FE, ⚙️ BE, :white_check_mark: CHECK

#87 Develop
  src/main/frontend/src/apis/test/auth.test.tsx
  src/main/frontend/src/apis/user/index.ts
  src/main/frontend/src/components/organisms/SignControl.tsx
  src/main/frontend/src/pages/Diary/Recommend.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/frontend/src/tools/devConsole.ts
  src/main/resources/application.properties
Labels: 🔮 SYNC

#92 Kkn1125/fe/about
  src/main/frontend/.env
  src/main/frontend/src/components/atoms/Brand.tsx
  src/main/frontend/src/components/atoms/Title.tsx
  src/main/frontend/src/components/common/WavesBG.tsx
  src/main/frontend/src/components/molecules/MessageBox.tsx
  src/main/frontend/src/components/organisms/DynamicSection.tsx
  src/main/frontend/src/components/organisms/FaceSign.tsx
  src/main/frontend/src/components/organisms/Footer.tsx
  src/main/frontend/src/components/organisms/Header.tsx
  src/main/frontend/src/components/organisms/SignControl.tsx
  src/main/frontend/src/components/templates/AuthLayout.tsx
  src/main/frontend/src/components/templates/DiaryLayout.tsx
  src/main/frontend/src/pages/About.tsx
  src/main/frontend/src/pages/Auth/SignIn.tsx
  src/main/frontend/src/pages/Auth/SignUp.tsx
  src/main/frontend/src/pages/Diary/Detail.tsx
  src/main/frontend/src/pages/Home.tsx
Labels: :lady_beetle: BUGFIX, ✖️ ADD, :hammer_and_wrench: UPDATE, 📄 TODO, ✨ FE, :white_check_mark: CHECK

#93 Develop
  src/main/frontend/.env
  src/main/frontend/src/components/atoms/Brand.tsx
  src/main/frontend/src/components/atoms/Title.tsx
  src/main/frontend/src/components/common/WavesBG.tsx
  src/main/frontend/src/components/molecules/MessageBox.tsx
  src/main/frontend/src/components/organisms/DynamicSection.tsx
  src/main/frontend/src/components/organisms/FaceSign.tsx
  src/main/frontend/src/components/organisms/Footer.tsx
  src/main/frontend/src/components/organisms/Header.tsx
  src/main/frontend/src/components/organisms/SignControl.tsx
  src/main/frontend/src/components/templates/AuthLayout.tsx
  src/main/frontend/src/components/templates/DiaryLayout.tsx
  src/main/frontend/src/pages/About.tsx
  src/main/frontend/src/pages/Auth/SignIn.tsx
  src/main/frontend/src/pages/Auth/SignUp.tsx
  src/main/frontend/src/pages/Diary/Detail.tsx
  src/main/frontend/src/pages/Diary/Recommend.tsx
  src/main/frontend/src/pages/Home.tsx
Labels: 🔮 SYNC

#95 Kkn1125/fe/security
  build.gradle
  src/main/frontend/.prettierrc
  src/main/frontend/package.json
  src/main/frontend/src/apis/auth/index.ts
  src/main/frontend/src/apis/user/index.ts
  src/main/frontend/src/apis/user/types.ts
  src/main/frontend/src/components/molecules/AvatarBox.tsx
  src/main/frontend/src/components/molecules/SwitchLabels.tsx
  src/main/frontend/src/components/organisms/DrawerBlock.tsx
  src/main/frontend/src/components/templates/DetailLayout.tsx
  src/main/frontend/src/contexts/UserProvider.tsx
  src/main/frontend/src/index.tsx
  src/main/frontend/src/models/MenuItem.ts
  src/main/frontend/src/pages/Auth/Profile.tsx
  src/main/frontend/src/pages/Auth/SignIn.tsx
  src/main/frontend/src/pages/Auth/SignUp.tsx
  src/main/frontend/src/pages/Diary/Recommend.tsx
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/frontend/src/pages/Home.tsx
  src/main/frontend/yarn.lock
  src/main/java/com/narang/web/config/SecurityConfiguration.java
  src/main/java/com/narang/web/entity/Authority.java
  src/main/java/com/narang/web/entity/User.java
  src/main/java/com/narang/web/filter/CustomAuthenticationManager.java
  src/main/java/com/narang/web/filter/CustomAuthenticationProcessingFilter.java
  src/main/java/com/narang/web/restController/UserRestController.java
  src/main/java/com/narang/web/service/CustomUserDetailsService.java
  src/main/java/com/narang/web/service/SecurityService.java
Labels: :lady_beetle: BUGFIX, ✖️ ADD, :hammer_and_wrench: UPDATE, 📄 TODO, ✨ FE, :white_check_mark: CHECK

#94 [BE][:hammer_and_wrench: FEAT]: spring security 및 jwt token 발행 구현 + 유…
  build.gradle
  src/main/java/com/narang/web/config/SecurityConfiguration.java
  src/main/java/com/narang/web/entity/Authority.java
  src/main/java/com/narang/web/entity/User.java
  src/main/java/com/narang/web/filter/CustomAuthenticationManager.java
  src/main/java/com/narang/web/filter/CustomAuthenticationProcessingFilter.java
  src/main/java/com/narang/web/restController/UserRestController.java
  src/main/java/com/narang/web/service/CustomUserDetailsService.java
  src/main/java/com/narang/web/service/SecurityService.java
Labels: :lady_beetle: BUGFIX, ✖️ ADD, :hammer_and_wrench: UPDATE, 🗂️ REF, 📄 TODO, ⚙️ BE, :white_check_mark: CHECK

#96 Develop
  build.gradle
  src/main/frontend/.prettierrc
  src/main/frontend/package.json
  src/main/frontend/src/apis/auth/index.ts
  src/main/frontend/src/apis/user/index.ts
  src/main/frontend/src/apis/user/types.ts
  src/main/frontend/src/components/molecules/AvatarBox.tsx
  src/main/frontend/src/components/molecules/SwitchLabels.tsx
  src/main/frontend/src/components/organisms/DrawerBlock.tsx
  src/main/frontend/src/components/templates/DetailLayout.tsx
  src/main/frontend/src/contexts/UserProvider.tsx
  src/main/frontend/src/index.tsx
  src/main/frontend/src/models/MenuItem.ts
  src/main/frontend/src/pages/Auth/Profile.tsx
  src/main/frontend/src/pages/Auth/SignIn.tsx
  src/main/frontend/src/pages/Auth/SignUp.tsx
  src/main/frontend/src/pages/Diary/Recommend.tsx
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/frontend/src/pages/Home.tsx
  src/main/frontend/yarn.lock
  src/main/java/com/narang/web/config/SecurityConfiguration.java
  src/main/java/com/narang/web/entity/Authority.java
  src/main/java/com/narang/web/entity/User.java
  src/main/java/com/narang/web/filter/CustomAuthenticationManager.java
  src/main/java/com/narang/web/filter/CustomAuthenticationProcessingFilter.java
  src/main/java/com/narang/web/restController/UserRestController.java
  src/main/java/com/narang/web/service/CustomUserDetailsService.java
  src/main/java/com/narang/web/service/SecurityService.java
Labels: 🔮 SYNC

#99 Ohoraming/fe/add
  src/main/frontend/src/apis/product/index.ts
  src/main/frontend/src/models/Product.ts
Labels: ✖️ ADD, ✨ FE, :white_check_mark: CHECK

#101 [FE/BE][:hammer_and_wrench: FEAT]: 프론트 sha256암호화 라이브러리 설치 + 안면 로그인 테 …
  build.gradle
  src/main/frontend/.env
  src/main/frontend/package.json
  src/main/frontend/src/apis/auth/index.ts
  src/main/frontend/src/apis/faceImage/index.ts
  src/main/frontend/src/apis/utils/fileupload.ts
  src/main/frontend/src/components/organisms/FaceSign.tsx
  src/main/frontend/src/models/FaceImage.ts
  src/main/frontend/src/models/IModel.ts
  src/main/frontend/src/models/User.ts
  src/main/frontend/src/pages/Home.tsx
  src/main/frontend/src/tools/utils.ts
  src/main/frontend/yarn.lock
  src/main/java/com/narang/web/mongoTemplate/UserTemplate.java
  src/main/java/com/narang/web/repository/UserRepositoryCustom.java
  src/main/java/com/narang/web/repository/UserRepositoryCustomImpl.java
  src/main/java/com/narang/web/restController/TestRestController.java
  src/main/java/com/narang/web/restController/UserRestController.java
  src/main/java/com/narang/web/service/UserService.java
Labels: ✖️ ADD, :hammer_and_wrench: UPDATE, 📄 TODO, ✨ FE, ⚙️ BE, :white_check_mark: CHECK

#102 [FE][:wrench: FIX]: 프로필 업데이트 구현 및 테스트 + 일기 수정 경로 추가 및 데이터 로딩 테스트 완료 +…
  src/main/frontend/src/App.tsx
  src/main/frontend/src/apis/diary/index.ts
  src/main/frontend/src/components/molecules/AvatarBox.tsx
  src/main/frontend/src/components/organisms/DynamicSection.tsx
  src/main/frontend/src/components/templates/DetailLayout.tsx
  src/main/frontend/src/pages/Auth/Profile.tsx
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/src/pages/Diary/index.tsx
Labels: ✖️ ADD, 📄 TODO, ✨ FE, :white_check_mark: CHECK, :exclamation: PROBLEM

#104 Develop
  build.gradle
  src/main/frontend/.env
  src/main/frontend/package.json
  src/main/frontend/src/App.tsx
  src/main/frontend/src/apis/auth/index.ts
  src/main/frontend/src/apis/diary/index.ts
  src/main/frontend/src/apis/faceImage/index.ts
  src/main/frontend/src/apis/product/index.ts
  src/main/frontend/src/apis/utils/fileupload.ts
  src/main/frontend/src/components/molecules/AvatarBox.tsx
  src/main/frontend/src/components/organisms/DynamicSection.tsx
  src/main/frontend/src/components/organisms/FaceSign.tsx
  src/main/frontend/src/components/templates/DetailLayout.tsx
  src/main/frontend/src/models/FaceImage.ts
  src/main/frontend/src/models/IModel.ts
  src/main/frontend/src/models/Product.ts
  src/main/frontend/src/models/User.ts
  src/main/frontend/src/pages/Auth/Profile.tsx
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/frontend/src/pages/Home.tsx
  src/main/frontend/src/tools/utils.ts
  src/main/frontend/yarn.lock
  src/main/java/com/narang/web/mongoTemplate/UserTemplate.java
  src/main/java/com/narang/web/repository/UserRepositoryCustom.java
  src/main/java/com/narang/web/repository/UserRepositoryCustomImpl.java
  src/main/java/com/narang/web/restController/TestRestController.java
  src/main/java/com/narang/web/restController/UserRestController.java
  src/main/java/com/narang/web/service/UserService.java
Labels: 🔮 SYNC

#108 [BE][:lady_beetle: HOTFIX]: comment service 누락 추가
  src/main/java/com/narang/web/service/CommentService.java
Labels: :lady_beetle: BUGFIX, :wrench: FIX, ⚙️ BE

#109 Develop
  src/main/java/com/narang/web/service/CommentService.java
Labels: 🔮 SYNC

#110 [FE][:wrench: HOTFIX]: 카드 default 제거 + recommend페이지 cart추가 예시 코드 작성
  src/main/frontend/src/models/User.ts
  src/main/frontend/src/pages/Diary/Recommend.tsx
  src/main/java/com/narang/web/entity/Cart.java
Labels: :wrench: FIX, ✨ FE, :white_check_mark: CHECK

#111 Develop
  src/main/frontend/src/models/User.ts
  src/main/frontend/src/pages/Diary/Recommend.tsx
  src/main/java/com/narang/web/entity/Cart.java
Labels: 🔮 SYNC

#113 [BE][:wrench: FIX]: 코드 컨벤션 관련 수정 [#112 참조]
  build.gradle
  src/main/frontend/src/pages/Home.tsx
  src/main/java/com/narang/web/config/SecurityConfiguration.java
  src/main/java/com/narang/web/entity/Comment.java
  src/main/java/com/narang/web/entity/Diary.java
  src/main/java/com/narang/web/entity/User.java
  src/main/java/com/narang/web/repository/CommentRepositoryCustom.java
  src/main/java/com/narang/web/repository/CommentRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/DiaryRepositoryCustom.java
  src/main/java/com/narang/web/repository/DiaryRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/EmotionRepositoryCustom.java
  src/main/java/com/narang/web/repository/EmotionRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/UserRepositoryCustom.java
  src/main/java/com/narang/web/repository/UserRepositoryCustomImpl.java
  src/main/java/com/narang/web/restController/CommentRestController.java
  src/main/java/com/narang/web/restController/DiaryRestController.java
  src/main/java/com/narang/web/restController/UserRestController.java
  src/main/java/com/narang/web/service/CommentService.java
  src/main/java/com/narang/web/service/DiaryService.java
  src/main/java/com/narang/web/service/EmotionService.java
  src/main/java/com/narang/web/service/UserService.java
Labels: :wrench: FIX, 🗂️ REF, ⚙️ BE

#114 Develop
  build.gradle
  src/main/frontend/src/pages/Home.tsx
  src/main/java/com/narang/web/config/SecurityConfiguration.java
  src/main/java/com/narang/web/entity/Comment.java
  src/main/java/com/narang/web/entity/Diary.java
  src/main/java/com/narang/web/entity/User.java
  src/main/java/com/narang/web/repository/CommentRepositoryCustom.java
  src/main/java/com/narang/web/repository/CommentRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/DiaryRepositoryCustom.java
  src/main/java/com/narang/web/repository/DiaryRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/EmotionRepositoryCustom.java
  src/main/java/com/narang/web/repository/EmotionRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/UserRepositoryCustom.java
  src/main/java/com/narang/web/repository/UserRepositoryCustomImpl.java
  src/main/java/com/narang/web/restController/CommentRestController.java
  src/main/java/com/narang/web/restController/DiaryRestController.java
  src/main/java/com/narang/web/restController/UserRestController.java
  src/main/java/com/narang/web/service/CommentService.java
  src/main/java/com/narang/web/service/DiaryService.java
  src/main/java/com/narang/web/service/EmotionService.java
  src/main/java/com/narang/web/service/UserService.java
Labels: 🔮 SYNC

#116 [FE/BE][:lady_beetle: HOTFIX]: 로그인 에러 수정
  src/main/frontend/src/apis/utils/fileupload.ts
  src/main/frontend/src/components/organisms/DrawerBlock.tsx
  src/main/frontend/src/components/organisms/FaceSign.tsx
  src/main/frontend/src/pages/Auth/Profile.tsx
  src/main/frontend/src/pages/Auth/SignUp.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/frontend/src/tools/devConsole.ts
  src/main/java/com/narang/web/restController/UserRestController.java
  src/main/java/com/narang/web/service/UserService.java
Labels: :lady_beetle: BUGFIX, ✨ FE, ⚙️ BE

#117 Develop
  src/main/frontend/src/apis/utils/fileupload.ts
  src/main/frontend/src/components/organisms/DrawerBlock.tsx
  src/main/frontend/src/components/organisms/FaceSign.tsx
  src/main/frontend/src/pages/Auth/Profile.tsx
  src/main/frontend/src/pages/Auth/SignUp.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/frontend/src/tools/devConsole.ts
  src/main/java/com/narang/web/restController/UserRestController.java
  src/main/java/com/narang/web/service/UserService.java
Labels: 🔮 SYNC

#118 Kkn1125/fe/diary
  src/main/frontend/src/apis/commonTypes.ts
  src/main/frontend/src/apis/user/index.ts
  src/main/frontend/src/apis/utils/fileupload.ts
  src/main/frontend/src/components/molecules/AvatarBox.tsx
  src/main/frontend/src/components/organisms/UserInfo.tsx
  src/main/frontend/src/models/PModel.ts
  src/main/frontend/src/pages/Auth/Profile.tsx
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/src/tools/utils.ts
Labels: :lady_beetle: BUGFIX, ✖️ ADD, :hammer_and_wrench: UPDATE, 📄 TODO, ✨ FE, :white_check_mark: CHECK

#119 Kkn1125/be/diary
  src/main/frontend/src/profiles/62f0bc8331925873285f3a47/6199fa6416a5f317d16331dafbf3f55b14fbe9e578e9989c94d816c3f1c5cc81.jpg
  src/main/java/com/narang/web/repository/DiaryRepositoryCustom.java
  src/main/java/com/narang/web/repository/DiaryRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/LikeRepositoryCustom.java
  src/main/java/com/narang/web/repository/LikeRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/UserRepositoryCustom.java
  src/main/java/com/narang/web/repository/UserRepositoryCustomImpl.java
  src/main/java/com/narang/web/restController/DiaryRestController.java
  src/main/java/com/narang/web/restController/LikeRestController.java
  src/main/java/com/narang/web/restController/UserRestController.java
  src/main/java/com/narang/web/service/DiaryService.java
  src/main/java/com/narang/web/service/LikeService.java
  src/main/java/com/narang/web/service/UserService.java
Labels: :wrench: FIX, ✖️ ADD, :hammer_and_wrench: UPDATE, ⚙️ BE

#120 Develop
  src/main/frontend/src/apis/commonTypes.ts
  src/main/frontend/src/apis/user/index.ts
  src/main/frontend/src/apis/utils/fileupload.ts
  src/main/frontend/src/components/molecules/AvatarBox.tsx
  src/main/frontend/src/components/organisms/UserInfo.tsx
  src/main/frontend/src/models/PModel.ts
  src/main/frontend/src/pages/Auth/Profile.tsx
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/src/profiles/62f0bc8331925873285f3a47/6199fa6416a5f317d16331dafbf3f55b14fbe9e578e9989c94d816c3f1c5cc81.jpg
  src/main/frontend/src/tools/utils.ts
  src/main/java/com/narang/web/repository/DiaryRepositoryCustom.java
  src/main/java/com/narang/web/repository/DiaryRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/LikeRepositoryCustom.java
  src/main/java/com/narang/web/repository/LikeRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/UserRepositoryCustom.java
  src/main/java/com/narang/web/repository/UserRepositoryCustomImpl.java
  src/main/java/com/narang/web/restController/DiaryRestController.java
  src/main/java/com/narang/web/restController/LikeRestController.java
  src/main/java/com/narang/web/restController/UserRestController.java
  src/main/java/com/narang/web/service/DiaryService.java
  src/main/java/com/narang/web/service/LikeService.java
  src/main/java/com/narang/web/service/UserService.java
Labels: 🔮 SYNC

#121 [FE][:wrench: FIX]: 일기 공개여부 변경 데이터 누락 현상 수정
  src/main/frontend/src/models/PModel.ts
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/src/profiles/62f0bc8331925873285f3a47/e109fea26c80332c346a479f349ee9c241d8ac1aae8fdd0e9252a88a56605fbb.jpg
Labels: :lady_beetle: BUGFIX, :white_check_mark: CHECK

#122 Develop
  src/main/frontend/src/models/PModel.ts
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/src/profiles/62f0bc8331925873285f3a47/e109fea26c80332c346a479f349ee9c241d8ac1aae8fdd0e9252a88a56605fbb.jpg
Labels: 🔮 SYNC

#127 Develop
  src/main/frontend/src/apis/cart/index.ts
  src/main/frontend/src/apis/product/index.ts
  src/main/frontend/src/pages/Diary/Graph.tsx
  src/main/java/com/narang/web/entity/Product.java
  src/main/java/com/narang/web/restController/ProductRestController.java
Labels: 🔮 SYNC

#131 Ohoraming/fe/feat
  src/main/frontend/src/pages/Diary/Graph.tsx
Labels: :hammer_and_wrench: UPDATE, ✨ FE, :white_check_mark: CHECK

#136 [FE][:hammer_and_wrench: FEAT]: 일기 댓글 테스트 + CommentContext 추가
  src/main/frontend/src/apis/diary/index.ts
  src/main/frontend/src/components/molecules/CommentItem.tsx
  src/main/frontend/src/components/organisms/CommentInsert.tsx
  src/main/frontend/src/components/organisms/CommentList.tsx
  src/main/frontend/src/components/templates/DetailLayout.tsx
  src/main/frontend/src/components/templates/DiaryLayout.tsx
  src/main/frontend/src/contexts/CommentProvider.tsx
  src/main/frontend/src/index.tsx
  src/main/frontend/src/models/Comment.ts
  src/main/frontend/src/models/PModel.ts
  src/main/frontend/src/pages/Diary/Detail.tsx
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/src/pages/Diary/index.tsx
Labels: :hammer_and_wrench: UPDATE, 📄 TODO, ✨ FE

#147 Develop
  build.gradle
  src/main/frontend/src/apis/auth/index.ts
  src/main/frontend/src/apis/comment/index.ts
  src/main/frontend/src/apis/diary/index.ts
  src/main/frontend/src/apis/faceImage/index.ts
  src/main/frontend/src/apis/like/index.ts
  src/main/frontend/src/apis/user/index.ts
  src/main/frontend/src/components/atoms/FavoritButton.tsx
  src/main/frontend/src/components/molecules/AvatarBox.tsx
  src/main/frontend/src/components/molecules/CommentItem.tsx
  src/main/frontend/src/components/molecules/MessageBox.tsx
  src/main/frontend/src/components/organisms/CommentInsert.tsx
  src/main/frontend/src/components/organisms/CommentList.tsx
  src/main/frontend/src/components/organisms/FaceSign.tsx
  src/main/frontend/src/components/organisms/UserInfo.tsx
  src/main/frontend/src/components/templates/DetailLayout.tsx
  src/main/frontend/src/components/templates/DiaryLayout.tsx
  src/main/frontend/src/contexts/CommentProvider.tsx
  src/main/frontend/src/index.tsx
  src/main/frontend/src/models/Comment.ts
  src/main/frontend/src/models/PModel.ts
  src/main/frontend/src/pages/Auth/Profile.tsx
  src/main/frontend/src/pages/Auth/SignIn.tsx
  src/main/frontend/src/pages/Auth/SignUp.tsx
  src/main/frontend/src/pages/Diary/Cart.tsx
  src/main/frontend/src/pages/Diary/Detail.tsx
  src/main/frontend/src/pages/Diary/Graph.tsx
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/frontend/src/profiles/62f20a46327b0412992d95f4/e109fea26c80332c346a479f349ee9c241d8ac1aae8fdd0e9252a88a56605fbb.jpg
  src/main/frontend/src/tools/utils.ts
  src/main/java/com/narang/web/entity/Comment.java
  src/main/java/com/narang/web/entity/Diary.java
  src/main/java/com/narang/web/entity/Emotion.java
  src/main/java/com/narang/web/entity/FaceImage.java
  src/main/java/com/narang/web/entity/Like.java
  src/main/java/com/narang/web/entity/Product.java
  src/main/java/com/narang/web/entity/User.java
  src/main/java/com/narang/web/entity/Whether.java
  src/main/java/com/narang/web/repository/UserRepositoryCustom.java
  src/main/java/com/narang/web/repository/UserRepositoryCustomImpl.java
  src/main/java/com/narang/web/restController/CommentRestController.java
  src/main/java/com/narang/web/restController/ProductRestController.java
  src/main/java/com/narang/web/restController/UserRestController.java
  src/main/java/com/narang/web/service/UserService.java
Labels: 🔮 SYNC

#148 [FE][:lady_beetle: HOTFIX]: 일기 커버 이미지 오류 수정
  src/main/frontend/src/pages/Diary/index.tsx
Labels: :lady_beetle: BUGFIX, :white_check_mark: CHECK

#149 Develop
  src/main/frontend/src/pages/Diary/index.tsx
Labels: 🔮 SYNC

#153 [BE][:hammer_and_wrench: FEAT]: ResponseEntity -> ObjectMapper 변경 + r…
  src/main/java/com/narang/web/repository/BillRepository.java
  src/main/java/com/narang/web/repository/BillRepositoryCustom.java
  src/main/java/com/narang/web/repository/BillRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/CartRepository.java
  src/main/java/com/narang/web/repository/CartRepositoryCustom.java
  src/main/java/com/narang/web/repository/CartRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/CommentRepositoryCustom.java
  src/main/java/com/narang/web/repository/CommentRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/EmotionRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/FaceImageRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/LikeRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/ProductRepository.java
  src/main/java/com/narang/web/repository/ProductRepositoryCustom.java
  src/main/java/com/narang/web/repository/ProductRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/UserRepositoryCustom.java
  src/main/java/com/narang/web/repository/UserRepositoryCustomImpl.java
  src/main/java/com/narang/web/restController/BillRestController.java
  src/main/java/com/narang/web/restController/CartRestController.java
  src/main/java/com/narang/web/restController/CommentRestController.java
  src/main/java/com/narang/web/restController/DiaryRestController.java
  src/main/java/com/narang/web/restController/EmotionRestController.java
  src/main/java/com/narang/web/restController/FaceImageRestController.java
  src/main/java/com/narang/web/restController/LikeRestController.java
  src/main/java/com/narang/web/restController/ProductRestController.java
  src/main/java/com/narang/web/restController/UserRestController.java
  src/main/java/com/narang/web/service/BillService.java
  src/main/java/com/narang/web/service/CartService.java
  src/main/java/com/narang/web/service/CommentService.java
  src/main/java/com/narang/web/service/CustomUserDetailsService.java
  src/main/java/com/narang/web/service/DiaryService.java
  src/main/java/com/narang/web/service/EmotionService.java
  src/main/java/com/narang/web/service/FaceImageService.java
  src/main/java/com/narang/web/service/ProductService.java
  src/main/java/com/narang/web/service/SecurityService.java
  src/main/java/com/narang/web/service/UserService.java
Labels: :hammer_and_wrench: UPDATE, 📄 TODO, ⚙️ BE, :white_check_mark: CHECK

#154 Develop
  src/main/java/com/narang/web/entity/Bill.java
  src/main/java/com/narang/web/entity/Cart.java
  src/main/java/com/narang/web/entity/Product.java
  src/main/java/com/narang/web/repository/BillRepository.java
  src/main/java/com/narang/web/repository/BillRepositoryCustom.java
  src/main/java/com/narang/web/repository/BillRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/CartRepository.java
  src/main/java/com/narang/web/repository/CartRepositoryCustom.java
  src/main/java/com/narang/web/repository/CartRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/CommentRepositoryCustom.java
  src/main/java/com/narang/web/repository/CommentRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/EmotionRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/FaceImageRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/LikeRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/ProductRepository.java
  src/main/java/com/narang/web/repository/ProductRepositoryCustom.java
  src/main/java/com/narang/web/repository/ProductRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/UserRepositoryCustom.java
  src/main/java/com/narang/web/repository/UserRepositoryCustomImpl.java
  src/main/java/com/narang/web/restController/BillRestController.java
  src/main/java/com/narang/web/restController/CartRestController.java
  src/main/java/com/narang/web/restController/CommentRestController.java
  src/main/java/com/narang/web/restController/DiaryRestController.java
  src/main/java/com/narang/web/restController/EmotionRestController.java
  src/main/java/com/narang/web/restController/FaceImageRestController.java
  src/main/java/com/narang/web/restController/LikeRestController.java
  src/main/java/com/narang/web/restController/ProductRestController.java
  src/main/java/com/narang/web/restController/UserRestController.java
  src/main/java/com/narang/web/service/BillService.java
  src/main/java/com/narang/web/service/CartService.java
  src/main/java/com/narang/web/service/CommentService.java
  src/main/java/com/narang/web/service/CustomUserDetailsService.java
  src/main/java/com/narang/web/service/DiaryService.java
  src/main/java/com/narang/web/service/EmotionService.java
  src/main/java/com/narang/web/service/FaceImageService.java
  src/main/java/com/narang/web/service/ProductService.java
  src/main/java/com/narang/web/service/SecurityService.java
  src/main/java/com/narang/web/service/UserService.java
Labels: 🔮 SYNC

#155 [FE][:wrench: FIX]: 로그아웃 토큰 삭제되지 않는 현상 수정 + 안면인식 로그인 위한 사진 업로드 오류 수정 …
  src/main/frontend/src/components/molecules/AvatarBox.tsx
  src/main/frontend/src/components/organisms/FaceSign.tsx
  src/main/frontend/src/pages/Auth/Profile.tsx
  src/main/frontend/src/upload/62f20a46327b0412992d95f4/0ffeed4605cb9ca1fe14ab308cc792dda0bacdb5306ece4fadceb39ff80f1d2c.jpg
  src/main/java/com/narang/web/repository/FaceImageRepositoryCustomImpl.java
  src/main/java/com/narang/web/restController/FaceImageRestController.java
  src/main/java/com/narang/web/restController/UserRestController.java
  src/main/java/com/narang/web/service/FaceImageService.java
Labels: :lady_beetle: BUGFIX, :hammer_and_wrench: UPDATE, ✨ FE, ⚙️ BE, :white_check_mark: CHECK

#156 Develop
  src/main/frontend/src/components/molecules/AvatarBox.tsx
  src/main/frontend/src/components/organisms/FaceSign.tsx
  src/main/frontend/src/pages/Auth/Profile.tsx
  src/main/frontend/src/upload/62f20a46327b0412992d95f4/0ffeed4605cb9ca1fe14ab308cc792dda0bacdb5306ece4fadceb39ff80f1d2c.jpg
  src/main/java/com/narang/web/repository/FaceImageRepositoryCustomImpl.java
  src/main/java/com/narang/web/restController/FaceImageRestController.java
  src/main/java/com/narang/web/restController/UserRestController.java
  src/main/java/com/narang/web/service/FaceImageService.java
Labels: 🔮 SYNC

#168 Ohoraming/fe/feat
  src/main/frontend/package.json
  src/main/frontend/src/components/molecules/MonthPicker.tsx
  src/main/frontend/src/components/molecules/WeekPicker.tsx
  src/main/frontend/src/components/templates/DiaryLayout.tsx
  src/main/frontend/src/pages/Diary/Graph.tsx
  src/main/frontend/yarn.lock
Labels: :wrench: FIX, ✖️ ADD, :hammer_and_wrench: UPDATE, ✨ FE

#176 [BE][:hammer_and_wrench: FEAT]: import 구문 정리 + readme 수정
  README.md
  build.gradle
  src/main/images/upload/62f20a46327b0412992d95f4/0ffeed4605cb9ca1fe14ab308cc792dda0bacdb5306ece4fadceb39ff80f1d2c.jpg
  src/main/java/com/narang/web/WebApplication.java
  src/main/java/com/narang/web/entity/Cart.java
  src/main/java/com/narang/web/entity/Comment.java
  src/main/java/com/narang/web/entity/User.java
  src/main/java/com/narang/web/filter/CustomAuthenticationProcessingFilter.java
  src/main/java/com/narang/web/repository/BillRepository.java
  src/main/java/com/narang/web/repository/CartRepository.java
  src/main/java/com/narang/web/repository/CommentRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/DiaryRepository.java
  src/main/java/com/narang/web/repository/DiaryRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/EmotionRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/FaceImageRepositoryCustom.java
  src/main/java/com/narang/web/repository/FaceImageRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/ProductRepository.java
  src/main/java/com/narang/web/repository/UserRepositoryCustom.java
  src/main/java/com/narang/web/repository/UserRepositoryCustomImpl.java
  src/main/java/com/narang/web/restController/BillRestController.java
  src/main/java/com/narang/web/restController/CartRestController.java
  src/main/java/com/narang/web/restController/CommentRestController.java
  src/main/java/com/narang/web/restController/FaceImageRestController.java
  src/main/java/com/narang/web/restController/ProductRestController.java
  src/main/java/com/narang/web/restController/UserRestController.java
  src/main/java/com/narang/web/service/CustomUserDetailsService.java
  src/main/java/com/narang/web/service/FaceImageService.java
  src/main/java/com/narang/web/service/UserService.java
  src/main/resources/static/asset-manifest.json
  src/main/resources/static/index.html
  yarn.lock
Labels: :hammer_and_wrench: UPDATE, 🗂️ REF, 📄 TODO, ⚙️ BE

#179 Develop
  src/main/frontend/src/apis/emotions/index.ts
  src/main/frontend/src/pages/Diary/Graph.tsx
  src/main/frontend/yarn.lock
  src/main/java/com/narang/web/repository/EmotionRepositoryCustom.java
  src/main/java/com/narang/web/repository/EmotionRepositoryCustomImpl.java
  src/main/java/com/narang/web/restController/EmotionRestController.java
  src/main/java/com/narang/web/service/EmotionService.java
  src/main/resources/static/asset-manifest.json
  src/main/resources/static/index.html
Labels: 🔮 SYNC

#181 Develop
  src/main/resources/static/asset-manifest.json
  src/main/resources/static/index.html
Labels: 🔮 SYNC

#183 [FE/BE][:wrench: FIX]: 중간점검 + 그래프 누락 코드 임시로 작성
  build.gradle
  src/main/frontend/.env
  src/main/frontend/src/components/molecules/WeekPicker.tsx
  src/main/frontend/src/components/organisms/UserInfo.tsx
  src/main/frontend/src/envPath.ts
  src/main/frontend/src/pages/Diary/Graph.tsx
  src/main/frontend/src/setupProxy.js
  src/main/frontend/src/tools/analyzer.ts
  src/main/frontend/src/tools/utils.ts
  src/main/frontend/yarn.lock
  src/main/java/com/narang/web/config/WebConfig.java
  src/main/java/com/narang/web/restController/EmotionRestController.java
  src/main/java/com/narang/web/restController/FaceImageRestController.java
  src/main/java/com/narang/web/restController/PapagoRestController.java
  src/main/java/com/narang/web/restController/UserRestController.java
  src/main/resources/application.properties
  src/main/resources/static/asset-manifest.json
  src/main/resources/static/index.html
Labels: :wrench: FIX, ✨ FE, ⚙️ BE, :white_check_mark: CHECK

#184 Develop
  build.gradle
  src/main/frontend/.env
  src/main/frontend/src/components/molecules/WeekPicker.tsx
  src/main/frontend/src/components/organisms/UserInfo.tsx
  src/main/frontend/src/envPath.ts
  src/main/frontend/src/pages/Diary/Graph.tsx
  src/main/frontend/src/setupProxy.js
  src/main/frontend/src/tools/analyzer.ts
  src/main/frontend/src/tools/utils.ts
  src/main/frontend/yarn.lock
  src/main/java/com/narang/web/config/WebConfig.java
  src/main/java/com/narang/web/restController/EmotionRestController.java
  src/main/java/com/narang/web/restController/FaceImageRestController.java
  src/main/java/com/narang/web/restController/PapagoRestController.java
  src/main/java/com/narang/web/restController/UserRestController.java
  src/main/resources/application.properties
  src/main/resources/static/asset-manifest.json
  src/main/resources/static/index.html
Labels: 🔮 SYNC

#194 Kkn1125/fe/hotfix
  build.gradle
  src/main/frontend/.gitignore
  src/main/frontend/package-lock.json
  src/main/frontend/src/components/atoms/OverflowContent.tsx
  src/main/frontend/src/components/molecules/AvatarBox.tsx
  src/main/frontend/src/components/molecules/MessageBox.tsx
  src/main/frontend/src/components/organisms/CommentList.tsx
  src/main/frontend/src/components/organisms/DynamicSection.tsx
  src/main/frontend/src/components/templates/DetailLayout.tsx
  src/main/frontend/src/pages/Diary/Detail.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/images/profiles/62f20a46327b0412992d95f4/6199fa6416a5f317d16331dafbf3f55b14fbe9e578e9989c94d816c3f1c5cc81.jpg
  src/main/images/upload/62f20a46327b0412992d95f4/0ffeed4605cb9ca1fe14ab308cc792dda0bacdb5306ece4fadceb39ff80f1d2c.jpg
Labels: :lady_beetle: BUGFIX, ✨ FE, :white_check_mark: CHECK

#195 Develop
  build.gradle
  src/main/frontend/.gitignore
  src/main/frontend/package-lock.json
  src/main/frontend/src/components/atoms/OverflowContent.tsx
  src/main/frontend/src/components/molecules/AvatarBox.tsx
  src/main/frontend/src/components/molecules/MessageBox.tsx
  src/main/frontend/src/components/organisms/CommentList.tsx
  src/main/frontend/src/components/organisms/DynamicSection.tsx
  src/main/frontend/src/components/templates/DetailLayout.tsx
  src/main/frontend/src/pages/Diary/Detail.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/images/profiles/62f20a46327b0412992d95f4/6199fa6416a5f317d16331dafbf3f55b14fbe9e578e9989c94d816c3f1c5cc81.jpg
  src/main/images/upload/62f20a46327b0412992d95f4/0ffeed4605cb9ca1fe14ab308cc792dda0bacdb5306ece4fadceb39ff80f1d2c.jpg
Labels: 🔮 SYNC

#203 [FE/BE][:hammer_and_wrench: FEAT]: 배포전 점검 및 버그 수정
  README.md
  src/main/frontend/README.md
  src/main/frontend/src/apis/emotions/index.ts
  src/main/frontend/src/apis/faceImage/index.ts
  src/main/frontend/src/apis/utils/fileupload.ts
  src/main/frontend/src/components/atoms/FavoritButton.tsx
  src/main/frontend/src/components/molecules/CommentItem.tsx
  src/main/frontend/src/components/molecules/FooterMenuList.tsx
  src/main/frontend/src/components/molecules/MessageBox.tsx
  src/main/frontend/src/components/molecules/WeekPicker.tsx
  src/main/frontend/src/components/organisms/FaceSign.tsx
  src/main/frontend/src/components/organisms/Footer.tsx
  src/main/frontend/src/components/templates/DiaryLayout.tsx
  src/main/frontend/src/models/MenuItem.ts
  src/main/frontend/src/models/PModel.ts
  src/main/frontend/src/pages/About.tsx
  src/main/frontend/src/pages/Auth/Profile.tsx
  src/main/frontend/src/pages/Auth/SignIn.tsx
  src/main/frontend/src/pages/Auth/SignUp.tsx
  src/main/frontend/src/pages/Diary/Graph.tsx
  src/main/frontend/src/pages/Diary/Recommend.tsx
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/images/profiles/62f20a46327b0412992d95f4/6199fa6416a5f317d16331dafbf3f55b14fbe9e578e9989c94d816c3f1c5cc81.jpg
  src/main/java/com/narang/web/entity/Bill.java
  src/main/java/com/narang/web/entity/Cart.java
  src/main/java/com/narang/web/entity/Product.java
  src/main/java/com/narang/web/entity/User.java
  src/main/java/com/narang/web/repository/EmotionRepositoryCustom.java
  src/main/java/com/narang/web/repository/EmotionRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/UserRepositoryCustomImpl.java
  src/main/java/com/narang/web/restController/UserRestController.java
  src/main/java/com/narang/web/service/EmotionService.java
  src/main/java/com/narang/web/service/UserService.java
Labels: :lady_beetle: BUGFIX, :hammer_and_wrench: UPDATE, ❌ DELETE, 📄 TODO, ✨ FE, ⚙️ BE, :white_check_mark: CHECK

#204 Develop
  README.md
  src/main/frontend/README.md
  src/main/frontend/src/apis/comment/index.ts
  src/main/frontend/src/apis/emotions/index.ts
  src/main/frontend/src/apis/faceImage/index.ts
  src/main/frontend/src/apis/utils/fileupload.ts
  src/main/frontend/src/components/atoms/FavoritButton.tsx
  src/main/frontend/src/components/molecules/CommentItem.tsx
  src/main/frontend/src/components/molecules/FooterMenuList.tsx
  src/main/frontend/src/components/molecules/MessageBox.tsx
  src/main/frontend/src/components/molecules/WeekPicker.tsx
  src/main/frontend/src/components/organisms/FaceSign.tsx
  src/main/frontend/src/components/organisms/Footer.tsx
  src/main/frontend/src/components/templates/DiaryLayout.tsx
  src/main/frontend/src/models/MenuItem.ts
  src/main/frontend/src/models/PModel.ts
  src/main/frontend/src/pages/About.tsx
  src/main/frontend/src/pages/Auth/Profile.tsx
  src/main/frontend/src/pages/Auth/SignIn.tsx
  src/main/frontend/src/pages/Auth/SignUp.tsx
  src/main/frontend/src/pages/Diary/Graph.tsx
  src/main/frontend/src/pages/Diary/Recommend.tsx
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/images/profiles/62f20a46327b0412992d95f4/6199fa6416a5f317d16331dafbf3f55b14fbe9e578e9989c94d816c3f1c5cc81.jpg
  src/main/java/com/narang/web/entity/Bill.java
  src/main/java/com/narang/web/entity/Cart.java
  src/main/java/com/narang/web/entity/Product.java
  src/main/java/com/narang/web/entity/User.java
  src/main/java/com/narang/web/repository/EmotionRepositoryCustom.java
  src/main/java/com/narang/web/repository/EmotionRepositoryCustomImpl.java
  src/main/java/com/narang/web/repository/UserRepositoryCustomImpl.java
  src/main/java/com/narang/web/restController/UserRestController.java
  src/main/java/com/narang/web/service/EmotionService.java
  src/main/java/com/narang/web/service/UserService.java
Labels: 🔮 SYNC

#205 [FE/BE][:hammer_and_wrench: FEAT]: 카카오 로그인 API 추가 + proxy 수정/추가 + 그래프…
  .gitignore
  src/main/frontend/src/App.tsx
  src/main/frontend/src/components/atoms/Title.tsx
  src/main/frontend/src/components/atoms/TyperTypography.tsx
  src/main/frontend/src/components/molecules/AvatarBox.tsx
  src/main/frontend/src/components/molecules/LoadingSkeleton.tsx
  src/main/frontend/src/components/molecules/MessageBox.tsx
  src/main/frontend/src/components/molecules/SocialSignIn.tsx
  src/main/frontend/src/components/organisms/DynamicSection.tsx
  src/main/frontend/src/components/organisms/Footer.tsx
  src/main/frontend/src/components/templates/DetailLayout.tsx
  src/main/frontend/src/components/templates/DetailLayoutSkeleton.tsx
  src/main/frontend/src/pages/Auth/Profile.tsx
  src/main/frontend/src/pages/Auth/SignIn.tsx
  src/main/frontend/src/pages/Diary/Graph.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/frontend/src/pages/Home.tsx
  src/main/frontend/src/setupProxy.js
  src/main/frontend/src/svg/Kakao.svg
  src/main/frontend/src/tools/Typer.js
  src/main/frontend/src/tools/utils.ts
  src/main/java/com/narang/web/config/WebConfig.java
  src/main/java/com/narang/web/repository/EmotionRepositoryCustomImpl.java
  src/main/java/com/narang/web/restController/KakaoRestController.java
  src/main/java/com/narang/web/restController/PapagoRestController.java
  src/main/resources/static/asset-manifest.json
  src/main/resources/static/index.html
Labels: :lady_beetle: BUGFIX, :wrench: FIX, ✖️ ADD, :hammer_and_wrench: UPDATE, ❌ DELETE, 📄 TODO, ✨ FE, ⚙️ BE, :white_check_mark: CHECK

#207 Develop
  .gitignore
  src/main/frontend/src/App.tsx
  src/main/frontend/src/components/atoms/Title.tsx
  src/main/frontend/src/components/atoms/TyperTypography.tsx
  src/main/frontend/src/components/molecules/AvatarBox.tsx
  src/main/frontend/src/components/molecules/LoadingSkeleton.tsx
  src/main/frontend/src/components/molecules/MessageBox.tsx
  src/main/frontend/src/components/molecules/SocialSignIn.tsx
  src/main/frontend/src/components/organisms/DynamicSection.tsx
  src/main/frontend/src/components/organisms/Footer.tsx
  src/main/frontend/src/components/templates/DetailLayout.tsx
  src/main/frontend/src/components/templates/DetailLayoutSkeleton.tsx
  src/main/frontend/src/pages/Auth/Profile.tsx
  src/main/frontend/src/pages/Auth/SignIn.tsx
  src/main/frontend/src/pages/Diary/Graph.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/frontend/src/pages/Home.tsx
  src/main/frontend/src/setupProxy.js
  src/main/frontend/src/svg/Kakao.svg
  src/main/frontend/src/tools/Typer.js
  src/main/frontend/src/tools/utils.ts
  src/main/java/com/narang/web/config/WebConfig.java
  src/main/java/com/narang/web/repository/EmotionRepositoryCustomImpl.java
  src/main/java/com/narang/web/restController/KakaoRestController.java
  src/main/java/com/narang/web/restController/PapagoRestController.java
  src/main/resources/static/asset-manifest.json
  src/main/resources/static/index.html
Labels: 🔮 SYNC

#208 [FE/BE][:wrench: FIX]: 텍스트 수정
  src/main/frontend/src/components/organisms/DynamicSection.tsx
  src/main/frontend/src/components/organisms/Footer.tsx
  src/main/frontend/src/pages/About.tsx
  src/main/frontend/src/pages/Diary/Graph.tsx
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/src/pages/Home.tsx
Labels: :wrench: FIX, ✨ FE

#209 Develop
  src/main/frontend/src/components/organisms/DynamicSection.tsx
  src/main/frontend/src/components/organisms/Footer.tsx
  src/main/frontend/src/pages/About.tsx
  src/main/frontend/src/pages/Diary/Graph.tsx
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/src/pages/Home.tsx
Labels: 🔮 SYNC

#210 [FE][:lady_beetle: HOTFIX]: 일기 삭제 확인 단계 추가 + 개발환경 콘솔 제거
  src/main/frontend/src/apis/commonTypes.ts
  src/main/frontend/src/components/templates/DetailLayout.tsx
  src/main/frontend/src/pages/Auth/Profile.tsx
  src/main/frontend/src/tools/utils.ts
Labels: :lady_beetle: BUGFIX

#214 [FE/BE][:hammer_and_wrench: FEAT]: 카카오 로그인 버그 수정 + 안면 로그인 버그 수정 + 댓글 …
  README.md
  src/main/frontend/package.json
  src/main/frontend/public/index.html
  src/main/frontend/src/App.tsx
  src/main/frontend/src/apis/auth/index.ts
  src/main/frontend/src/components/molecules/AvatarBox.tsx
  src/main/frontend/src/components/molecules/FooterMenuList.tsx
  src/main/frontend/src/components/organisms/FaceSign.tsx
  src/main/frontend/src/components/templates/DetailLayout.tsx
  src/main/frontend/src/pages/Auth/Profile.tsx
  src/main/frontend/src/pages/Auth/SignIn.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/frontend/src/pages/Home.tsx
  src/main/frontend/src/tools/utils.ts
  src/main/images/upload/62f20a46327b0412992d95f4/0ffeed4605cb9ca1fe14ab308cc792dda0bacdb5306ece4fadceb39ff80f1d2c.jpg
  src/main/java/com/narang/web/controller/IndexController.java
  src/main/java/com/narang/web/controller/KakaoController.java
  src/main/java/com/narang/web/restController/KakaoRestController.java
  src/main/java/com/narang/web/service/UserService.java
Labels: :lady_beetle: BUGFIX, ✖️ ADD, :hammer_and_wrench: UPDATE, ❌ DELETE, 🗂️ REF, 📄 TODO, ✨ FE, ⚙️ BE, :white_check_mark: CHECK, :exclamation: PROBLEM, :bookmark_tabs: Documentify

#215 Develop
  README.md
  src/main/frontend/package.json
  src/main/frontend/public/index.html
  src/main/frontend/src/App.tsx
  src/main/frontend/src/apis/auth/index.ts
  src/main/frontend/src/components/molecules/AvatarBox.tsx
  src/main/frontend/src/components/molecules/FooterMenuList.tsx
  src/main/frontend/src/components/organisms/FaceSign.tsx
  src/main/frontend/src/components/templates/DetailLayout.tsx
  src/main/frontend/src/pages/Auth/Profile.tsx
  src/main/frontend/src/pages/Auth/SignIn.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/frontend/src/pages/Home.tsx
  src/main/frontend/src/tools/utils.ts
  src/main/images/upload/62f20a46327b0412992d95f4/0ffeed4605cb9ca1fe14ab308cc792dda0bacdb5306ece4fadceb39ff80f1d2c.jpg
  src/main/java/com/narang/web/controller/IndexController.java
  src/main/java/com/narang/web/controller/KakaoController.java
  src/main/java/com/narang/web/restController/KakaoRestController.java
  src/main/java/com/narang/web/service/UserService.java
Labels: 🔮 SYNC

#220 Develop
  build.gradle
  src/main/frontend/src/App.tsx
  src/main/frontend/src/components/atoms/OverflowContent.tsx
  src/main/frontend/src/components/molecules/AvatarBox.tsx
  src/main/frontend/src/components/molecules/CommentItem.tsx
  src/main/frontend/src/components/molecules/LoadingSkeleton.tsx
  src/main/frontend/src/components/molecules/PopupAlert.tsx
  src/main/frontend/src/components/molecules/TextFieldSet.tsx
  src/main/frontend/src/components/organisms/CommentInsert.tsx
  src/main/frontend/src/components/organisms/CommentList.tsx
  src/main/frontend/src/components/organisms/FaceSign.tsx
  src/main/frontend/src/components/organisms/Footer.tsx
  src/main/frontend/src/components/organisms/SignControl.tsx
  src/main/frontend/src/components/templates/DetailLayout.tsx
  src/main/frontend/src/components/templates/DetailLayoutSkeleton.tsx
  src/main/frontend/src/components/templates/DiaryLayout.tsx
  src/main/frontend/src/contexts/CommentProvider.tsx
  src/main/frontend/src/models/Cart.ts
  src/main/frontend/src/pages/Auth/Profile.tsx
  src/main/frontend/src/pages/Auth/SignIn.tsx
  src/main/frontend/src/pages/Diary/Cart.tsx
  src/main/frontend/src/pages/Diary/Detail.tsx
  src/main/frontend/src/pages/Diary/Recommend.tsx
  src/main/frontend/src/pages/Diary/WriteForm.tsx
  src/main/frontend/src/pages/Diary/index.tsx
  src/main/frontend/src/tools/utils.ts
  src/main/java/com/narang/web/service/DiaryService.java
Labels: 🔮 SYNC

#221 [FE/BE][:hammer_and_wrench: FEAT]: 로고 제작 및 적용 + 안면 인식 로그인 UI 변경 + 안면인…
  src/main/frontend/public/android-icon-144x144.png
  src/main/frontend/public/android-icon-192x192.png
  src/main/frontend/public/android-icon-36x36.png
  src/main/frontend/public/android-icon-48x48.png
  src/main/frontend/public/android-icon-72x72.png
  src/main/frontend/public/android-icon-96x96.png
  src/main/frontend/public/apple-icon-114x114.png
  src/main/frontend/public/apple-icon-120x120.png
  src/main/frontend/public/apple-icon-144x144.png
  src/main/frontend/public/apple-icon-152x152.png
  src/main/frontend/public/apple-icon-180x180.png
  src/main/frontend/public/apple-icon-57x57.png
  src/main/frontend/public/apple-icon-60x60.png
  src/main/frontend/public/apple-icon-72x72.png
  src/main/frontend/public/apple-icon-76x76.png
  src/main/frontend/public/apple-icon-precomposed.png
  src/main/frontend/public/apple-icon.png
  src/main/frontend/public/browserconfig.xml
  src/main/frontend/public/favicon-16x16.png
  src/main/frontend/public/favicon-32x32.png
  src/main/frontend/public/favicon-96x96.png
  src/main/frontend/public/favicon.ico
  src/main/frontend/public/index.html
  src/main/frontend/public/logo/narang-bw.png
  src/main/frontend/public/logo/narang-color-full.png
  src/main/frontend/public/logo/narang-color-short.png
  src/main/frontend/public/manifest.json
  src/main/frontend/public/ms-icon-144x144.png
  src/main/frontend/public/ms-icon-150x150.png
  src/main/frontend/public/ms-icon-310x310.png
  src/main/frontend/public/ms-icon-70x70.png
  src/main/frontend/src/App.tsx
  src/main/frontend/src/components/atoms/Brand.tsx
  src/main/frontend/src/components/molecules/PopupAlert.tsx
  src/main/frontend/src/components/organisms/DrawerBlock.tsx
  src/main/frontend/src/components/organisms/FaceSign.tsx
  src/main/frontend/src/components/organisms/Header.tsx
  src/main/frontend/src/pages/About.tsx
  src/main/frontend/src/pages/Auth/SignIn.tsx
  src/main/frontend/src/tools/utils.ts
Labels: :hammer_and_wrench: UPDATE, 📄 TODO, ✨ FE, ⚙️ BE, :white_check_mark: CHECK

#222 Develop
  src/main/frontend/public/android-icon-144x144.png
  src/main/frontend/public/android-icon-192x192.png
  src/main/frontend/public/android-icon-36x36.png
  src/main/frontend/public/android-icon-48x48.png
  src/main/frontend/public/android-icon-72x72.png
  src/main/frontend/public/android-icon-96x96.png
  src/main/frontend/public/apple-icon-114x114.png
  src/main/frontend/public/apple-icon-120x120.png
  src/main/frontend/public/apple-icon-144x144.png
  src/main/frontend/public/apple-icon-152x152.png
  src/main/frontend/public/apple-icon-180x180.png
  src/main/frontend/public/apple-icon-57x57.png
  src/main/frontend/public/apple-icon-60x60.png
  src/main/frontend/public/apple-icon-72x72.png
  src/main/frontend/public/apple-icon-76x76.png
  src/main/frontend/public/apple-icon-precomposed.png
  src/main/frontend/public/apple-icon.png
  src/main/frontend/public/browserconfig.xml
  src/main/frontend/public/favicon-16x16.png
  src/main/frontend/public/favicon-32x32.png
  src/main/frontend/public/favicon-96x96.png
  src/main/frontend/public/favicon.ico
  src/main/frontend/public/index.html
  src/main/frontend/public/logo/narang-bw.png
  src/main/frontend/public/logo/narang-color-full.png
  src/main/frontend/public/logo/narang-color-short.png
  src/main/frontend/public/manifest.json
  src/main/frontend/public/ms-icon-144x144.png
  src/main/frontend/public/ms-icon-150x150.png
  src/main/frontend/public/ms-icon-310x310.png
  src/main/frontend/public/ms-icon-70x70.png
  src/main/frontend/src/App.tsx
  src/main/frontend/src/components/atoms/Brand.tsx
  src/main/frontend/src/components/molecules/PopupAlert.tsx
  src/main/frontend/src/components/organisms/DrawerBlock.tsx
  src/main/frontend/src/components/organisms/FaceSign.tsx
  src/main/frontend/src/components/organisms/Header.tsx
  src/main/frontend/src/pages/About.tsx
  src/main/frontend/src/pages/Auth/SignIn.tsx
  src/main/frontend/src/tools/utils.ts
Labels: 🔮 SYNC

#223 [COMMON][:wrench: FIX]: README.md git 및 영상 추가 + 팝업 수정 + 로고 수정 반영
  README.md
  build.gradle
  src/main/frontend/src/App.tsx
  src/main/frontend/src/components/atoms/Brand.tsx
  src/main/frontend/src/components/molecules/PopupAlert.tsx
  src/main/frontend/src/components/organisms/DrawerBlock.tsx
Labels: :wrench: FIX, 📄 TODO, ✨ FE, :white_check_mark: CHECK

#224 Develop
  README.md
  build.gradle
  src/main/frontend/src/App.tsx
  src/main/frontend/src/components/atoms/Brand.tsx
  src/main/frontend/src/components/molecules/PopupAlert.tsx
  src/main/frontend/src/components/organisms/DrawerBlock.tsx
Labels: 🔮 SYNC
